# Generated by Django 2.2.5 on 2019-09-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    
    dependencies = [
    ]
    
    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('source_name', models.CharField(max_length=20)),
                ('source_url', models.URLField()),
                ('body', models.CharField(max_length=5000)),
            ],
        ),
    ]
