# Generated by Django 2.2.5 on 2019-09-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0001_initial'),
    ]
    
    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='source_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='title',
            field=models.TextField(),
        ),
    ]
